### ISSUE TITLE
Readlink api not return correctly in the frontend

### ISSUE THREAD

**Issue by Rizary** [ARK-Builders/ARK-Shelf-Desktop#55]
![image](https://github.com/ARK-Builders/ARK-Shelf-Desktop/assets/7221768/edff92a9-4701-49ec-865a-39eed04efb1a)

**Comment by kirillt** [comment]
@Rizary am I right that the problem on screenshot is that we have 2 links read in `arklib`, but only 1 displayed in GUI?

**Comment by Rizary** [comment]
it's fixed on #50
